hub: LOG_LEVEL=debug ../bin/selenodium-grid --config conf-hub.json
selenium-hub: ./selenium-server -role hub -hubConfig conf-hub.json
node: ./selenium-server -role node -nodeConfig conf-node.json -port $PORT
